name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Test
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: make test
      # run: go test -v ./...
